name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run deployment
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/github_actions_rsa
          echo "$PRIVATE_RSA_KEY" > ~/.ssh/github_actions_rsa
          chmod 600 ~/.ssh/github_actions_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/github_actions_rsa
          ssh -tt ${{ secrets.REMOTE_HOST }}
          cd maries-sagofoto-server
          git pull
          pm2 restart ts-node -- src/index.ts
        env:
          PRIVATE_RSA_KEY: ${{ secrets.RSA_KEY }}
