# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: npm install && npm run test:ci
